version: 2.1


executors:
  node:
    docker:
      - image: circleci/node:10-browsers

  rust:
    docker:
      - image: oasislabs/rust:latest
    environment:
      PATH: /root/.local/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-2019-08-26-x86_64-unknown-linux-gnu/lib
    resource_class: xlarge


commands:
  install_oasis:
    steps:
      - run:
          name: Install Tools
          command: |
            apt-get -qq update
            apt-get -qq install python curl git gcc
            curl --proto '=https' --tlsv1.2 -sSL https://get.oasis.dev | python - --toolchain 19.41
            npm install -g lerna
            npm install -g yarn


jobs:
  build:
    executor: node

    steps:
      - checkout
      - run: |
          yarn
          yarn lint
          yarn build
          yarn test
          yarn coverage
      - run:
          # create an output directory with all the artifacts
          # generated by the build
          rm -rf output; mkdir -p output; for package in $(ls packages); do mkdir output/$package; cp -r  packages/$package/dist/* output/$package/; done

      - store_artifacts:
          path: output
      - persist_to_workspace:
          root: .
          paths:
            - output

  # Note that the test-e2e job uses a different executor because it requires
  # the ability to build the oasis toolchain, while the build job requires
  # the ability to run browser based tests.
  test-e2e:
    executor: rust
    steps:
      - checkout
      - install_oasis
      - run: yarn && yarn build
      - run: pushd packages/client/test/e2e && oasis build && popd
      - run: oasis-chain > /tmp/oasis-chain.log & yarn test:e2e


workflows:
  version: 2
  build:
    jobs:
      - build
      - test-e2e
